icon_names=[
    "menu",
    "loupe",
    "floppy",
    "computer",
    "star-filled-rounded",
    "dock-left",
    "task",
    "sonar",
    "check-round-outline2",
    "checkmark",
    "check-round-outline-whole",
    "left",
    "warning",
    "flag-outline-thin",
    "flag-outline-thick",
    "flag-filled",
    "work-week",
    "alarm",
    "plus",
    "x-circular",
    "small-x",
    "info",
    "editor",
    "pencil-and-paper",
    "update",
    "clipboard",
    "image-adjust-brightness",
    "file-cabinet",
    "star-outline-rounded",
    "controls",
    "dark-mode",
    "list-large",
    "dock-left",
    "horizontal-arrows",
    "size-vertically",
]